In [1]:
import pandas as pd
import numpy as np


In [2]:
data=pd.read_csv("pima-data.csv")

In [3]:
data.head(4)

num_preg  glucose_conc  diastolic_bp  thickness  insulin   bmi  diab_pred  \
0         6           148            72         35        0  33.6      0.627   
1         1            85            66         29        0  26.6      0.351   
2         8           183            64          0        0  23.3      0.672   
3         1            89            66         23       94  28.1      0.167   

   age    skin  diabetes  
0   50  1.3790      True  
1   31  1.1426     False  
2   32  0.0000      True  
3   21  0.9062     False

In [4]:
data.shape

(768, 10)

In [5]:
data.isnull().sum()

num_preg        0
glucose_conc    0
diastolic_bp    0
thickness       0
insulin         0
bmi             0
diab_pred       0
age             0
skin            0
diabetes        0
dtype: int64

In [6]:
y=pd.get_dummies(data['diabetes'],drop_first=True)
y.head()

True
0     1
1     0
2     1
3     0
4     1

In [7]:
x=data.drop('diabetes',axis=1)

In [8]:
from sklearn.impute import SimpleImputer

In [9]:
imputer=SimpleImputer(missing_values=0,strategy='mean')

In [10]:
x1=imputer.fit_transform(x)

In [11]:
x1=pd.DataFrame(x1,columns=x.columns)

In [12]:
x1.head()

num_preg  glucose_conc  diastolic_bp  thickness     insulin   bmi  \
0  6.000000         148.0          72.0   35.00000  155.548223  33.6   
1  1.000000          85.0          66.0   29.00000  155.548223  26.6   
2  8.000000         183.0          64.0   29.15342  155.548223  23.3   
3  1.000000          89.0          66.0   23.00000   94.000000  28.1   
4  4.494673         137.0          40.0   35.00000  168.000000  43.1   

   diab_pred   age      skin  
0      0.627  50.0  1.379000  
1      0.351  31.0  1.142600  
2      0.672  32.0  1.148645  
3      0.167  21.0  0.906200  
4      2.288  33.0  1.379000

In [16]:
from sklearn.preprocessing import StandardScaler,MinMaxScaler
# scaler=StandardScaler()
scaler=MinMaxScaler()
scaled=scaler.fit_transform(x1)

In [17]:
scaled=pd.DataFrame(scaled,columns=x1.columns)

In [18]:
scaled.head()

num_preg  glucose_conc  diastolic_bp  thickness   insulin       bmi  \
0  0.312500      0.670968      0.489796   0.304348  0.170130  0.314928   
1  0.000000      0.264516      0.428571   0.239130  0.170130  0.171779   
2  0.437500      0.896774      0.408163   0.240798  0.170130  0.104294   
3  0.000000      0.290323      0.428571   0.173913  0.096154  0.202454   
4  0.218417      0.600000      0.163265   0.304348  0.185096  0.509202   

   diab_pred       age      skin  
0   0.234415  0.483333  0.304348  
1   0.116567  0.166667  0.239130  
2   0.253629  0.183333  0.240798  
3   0.038002  0.000000  0.173913  
4   0.943638  0.200000  0.304348

In [19]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(scaled, y, test_size=0.33, random_state=42)

In [20]:
from sklearn.ensemble import RandomForestClassifier
random=RandomForestClassifier()
random.fit(x_train,y_train)

c:\users\cg-dte\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


RandomForestClassifier()

In [21]:
random_pred=random.predict(x_test)

In [22]:
from sklearn.metrics import confusion_matrix,accuracy_score
confusion_matrix(y_test,random_pred)

array([[134,  34],
       [ 30,  56]], dtype=int64)

In [23]:
accuracy_score(y_test,random_pred)

0.7480314960629921

In [25]:
from sklearn.linear_model import LogisticRegression
log=LogisticRegression()
log.fit(x_train,y_train)
log_pred=log.predict(x_test)

c:\users\cg-dte\appdata\local\programs\python\python37\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


In [26]:
confusion_matrix(y_test,log_pred)

array([[142,  26],
       [ 37,  49]], dtype=int64)

In [27]:
accuracy_score(y_test,log_pred)

0.7519685039370079

In [30]:
from sklearn.model_selection import cross_val_score
score=cross_val_score(log,x,y,cv=10,scoring='accuracy')

c:\users\cg-dte\appdata\local\programs\python\python37\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
c:\users\cg-dte\appdata\local\programs\python\python37\lib\site-packages\sklearn\linear_model\_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
c:\users\cg-dte\appdata\local\programs\python\python37\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed 

In [31]:
score

array([0.72727273, 0.77922078, 0.80519481, 0.71428571, 0.74025974,
       0.77922078, 0.81818182, 0.80519481, 0.73684211, 0.81578947])

In [32]:
score.mean()

0.7721462747778538